/**
 * FreeRDP: A Remote Desktop Protocol Implementation
 * DevolutionsRdp - Static Channel Symbol References
 *
 * Copyright 2025 Devolutions Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <winpr/wtypes.h>

/**
 * This file contains stub references to static channel tables and entry points
 * to force the linker to include them from libfreerdp-client.
 *
 * Without these references, the linker may discard the channel symbols
 * from the static library since nothing directly calls them.
 * The actual channel loading happens through function pointer tables
 * that are populated at build time.
 */

/* Declare external static channel tables from freerdp-client */
#ifdef __cplusplus
extern "C"
{
#endif

	/* Main static channel tables that freerdp_channels_load_static_addin_entry uses */
	typedef struct
	{
		const char* name;
		void* entry;
	} STATIC_ENTRY_TABLE_STUB;

	typedef struct
	{
		const char* name;
		const char* subsystem;
		void* entry;
	} STATIC_SUBSYSTEM_ENTRY_STUB;

	typedef struct
	{
		const char* name;
		const char* entryName;
		void* entry;
		const void* subsystemTable;
	} STATIC_ADDIN_TABLE_STUB;

	/* These are the actual tables generated by CMake in channels/client/tables.c */
	extern const STATIC_ENTRY_TABLE_STUB CLIENT_STATIC_ENTRY_TABLES[];
	extern const STATIC_ADDIN_TABLE_STUB CLIENT_STATIC_ADDIN_TABLE[];
	extern const STATIC_SUBSYSTEM_ENTRY_STUB CLIENT_RDPECAM_SUBSYSTEM_TABLE[];

	/* rdpecam entry points */
	extern UINT rdpecam_DVCPluginEntry(void* pEntryPoints);
	extern UINT v4l_freerdp_rdpecam_client_subsystem_entry(void* pEntryPoints);

#ifdef __cplusplus
}
#endif

/**
 * Force linker to include static channel tables and symbols.
 * This function is never called at runtime - it exists solely to create
 * references to the static tables so the linker includes them.
 */
const void** devolutions_rdp_force_static_channel_symbols(void)
{
	static const void* symbols[] = {
		/* Reference the main static tables - these are what freerdp_channels_load_static_addin_entry looks up */
		(const void*)CLIENT_STATIC_ENTRY_TABLES,
		(const void*)CLIENT_STATIC_ADDIN_TABLE,
		(const void*)CLIENT_RDPECAM_SUBSYSTEM_TABLE,
		/* Also reference the entry points themselves */
		(const void*)rdpecam_DVCPluginEntry,
		(const void*)v4l_freerdp_rdpecam_client_subsystem_entry,
		NULL
	};

	return symbols;
}
